"""empty message

Revision ID: 30df819ecc21
Revises: 2c436d5cb178
Create Date: 2019-11-12 07:51:01.020172

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '30df819ecc21'
down_revision = '2c436d5cb178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modulelogs_app',
    sa.Column('job_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('app_name', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=128), nullable=False),
    sa.Column('date_created', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modulelogs_app')
    # ### end Alembic commands ###
